### ISSUE TITLE
Awesome bot

### ISSUE THREAD

**Issue by dexstar007** [FKLC/WhatsAppToDiscord#1]
I'm having a lot of problems to even make it to work most of the times. I got this problem
Timed out. Please rescan QR Code. error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

But is a bit **strange** sometimes works fine without any issue.

I'm not sure why this happens at all.

Hope you can help me.

Have a nice day!

**Comment by FKLC** [comment]
I just updated dependencies and it is working again. You can download latest release from [here](https://github.com/FKLC/WhatsAppToDiscord/releases/latest/download/WA2DC.exe) or you can just build yourself by updating to the latest dependencies and building it again.

If your problem is solved please don't forget to close the issue.

**Comment by dexstar007** [comment]
**Awesome**!! Thanks.
