### ISSUE TITLE
you did not specify how it works

### ISSUE THREAD

**Issue by sh1vpatel** [FKLC/WhatsAppToDiscord#13]
No explanation of working and the motive of this code

**Comment by FKLC** [comment]
Every function is less than 100 lines and have self-explanatory names. Terms like jid is from the libraries. Other than that, I tried to keep everything organized but it probably isn't because I hate Go and the only reason for choosing it was, Go have a better WhatsApp Web library than Python, JS and, Rust. So, excuse me but I'm not willing to explain the code as it is IMO already pretty self-explanatory.
