### ISSUE TITLE
How can I modify the channel in the chats file?

### ISSUE THREAD

**Issue by JasperTheMinecraftDev** [FKLC/WhatsAppToDiscord#147]
Tried to modify it but it crashes as the webhook is gone.

How can I change the webhook? Can't find that in the JSON file.
And is there a better/official way to do it?

**Comment by FKLC** [comment]
Depends on what you mean by modifying it. What are you trying to do? To add/repair a channel, this is the schema.

```json
"number/groupJid/status@s.whatsapp.net/g.us/broadcast": {
    "id": "webhook id",
    "type": "Incoming",
    "token": "webhook token",
    "channelId": "channel id of the conversation"
  }
```

If you want to use an already existing channel as a chat channel, the easiest way would be to start a new conversation, then stop the bot so that the chat will be saved to chats. This way you'll get jid of the group. Then go back to old channel that you want to use, and right click > Edit Channel > Integrations > Webhooks 
- Delete the old webhook 
- [CTRL + SHIFT + I](https://github.com/FKLC/DiscordConsoleHacks#enabling-discord-console) to open dev tools and switch to `Network` tab 
- Click `Create Webhook` button on Discord
- Then on the Network tab, you'll see two `webhooks` entries > Click the first one > Preview
- Then you'll see something like this:
```json
{
    "application_id": null,
    "avatar": null,
    "channel_id": "COPY THIS TO channelId",
    "guild_id": "...",
    "id": "COPY THIS TO id",
    "name": "Captain Hook",
    "type": 1,
    "user": { },
    "token": "COPY THIS TO token",
    "url": "..."
}
```
- Then copy those info to the previously created entry in `chats` file.

This should be all. Just start the back again, and it should start working.

**Comment by FKLC** [comment]
yeah, ID is the webhook ID and channel id is the channel id. you can't get the previous webhooks token, that's why we create a new webhook. the old one won't work.
