### ISSUE TITLE
Would it be possible to tweak it a bit?

### ISSUE THREAD

**Issue by DAMmcpe** [FKLC/WhatsAppToDiscord#15]
Im using this at the moment for a bridge between our whatsapp class and our discord class group.
Would it be possible that messages from users in the discord appear in front of the message (Like [DAM] Hi)?

**Comment by FKLC** [comment]
Please see if the latest release is working for you. Quick notes: Because you already have the old version, after downloading the new version, run it once and stop it, so it can add related lines to the `settings.json`. Then follow the instructions below or in the `README` file. 
### Prefixing Messages Sent from Discord
If you share your WhatsApp conversation with multiple people, this setting allows you to prefix messages with Discord usernames. To enable:
1. Open `settings.json` with your choice of text editor
1. Move to the line `"DiscordPrefix": false,`
1. Change the `false` to `true`


Feel free to close the issue if it is working.

**Comment by DAMmcpe** [comment]
where do i find the config?

**Comment by FKLC** [comment]
Have you ever run the program? Once you run and follow the setup process, the program should create a setting file called `settings.json` in the same folder. This is where you will find the line `"DiscordPrefix": false,` and change the `false` to `true`
