### ISSUE TITLE
Invalid Token 

### ISSUE THREAD

**Issue by ChickenBizkit9** [FKLC/WhatsAppToDiscord#151]
**Describe the bug**

**To Reproduce**
1. Type '...'
2. Interact with the bot
3. See error

**Expected behavior**

**Logs**
If needed add your logs.txt after redacti
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/11967871/logs.txt)
ng any private information.

**Platform**
 - OS: [e.g. Windows, MacOS, Linux]

**Additional context**

**Comment by AngelDustArt** [comment]
Today, after resetting my phone and consequently WhatsApp connections, I tried to start the bot but it gave me an error, especially because there was an update. It prompted me to scan the QR code, but when I tried using the one at the top of the control room chat, it didn't work. Is there a way to generate QR codes? (I don't know if it's the same problem or a similar one)

**Comment by FKLC** [comment]
Deleting the folder `baileys` in `storage` folder should fix this and force bot to do a new qr code scan. Also closing the original issue due to inactivity.
