### ISSUE TITLE
Bot not sending QR code in the #control-room channel

### ISSUE THREAD

**Issue by jacquespillet** [FKLC/WhatsAppToDiscord#172]
**Describe the bug**
I follow all the steps in the Setup page with the Windows .exe file (WA2DC.exe), but when the bot joins the server, it does create the #control-room channel, but doesn't post the QR code as described in the Setup page.
I don't know if it's related, but when I start the .exe, it doesn't create the storage folder in the same directory, I had to create it myself.
It then gets populated with a few files.

**To Reproduce**
Follow all the steps in the Setup page

**Expected behavior**
I'm expecting the bot to send the QR code in the #control-room channel

**Logs**
{"level":30,"time":1701272767808,"pid":10664,"hostname":"GYFLYM","version":"v0.10.22","msg":"Starting"}
{"level":30,"time":1701272768109,"pid":10664,"hostname":"GYFLYM","version":"v0.10.22","msg":"Update checked."}
{"level":30,"time":1701272768110,"pid":10664,"hostname":"GYFLYM","version":"v0.10.22","msg":"Conversion completed."}

**Platform**
 - OS: Windows

**Comment by FKLC** [comment]
Hmm, do you not have anything in your logs? Is this all? I can't really tell what went wrong because there's no error message or any exit message, so unfortunately I don't know what would cause this.

**Comment by FKLC** [comment]
> Were you able to reproduce the bug ?

Unfortunately no.

>  Do you think this could be due to some parameters on our discord server, or with some permission issues with the user who invites the bot ?

I don't think so. Your server allows sending images right? Otherwise, if the person that invited bot has Manage Channels, Manage Webhooks, and Manage Messages permissions, it should be fine. 

>  Do you think it's worth us trying an older version of the bot ?

No, I don't think it will make a difference.


All things aside, have you tried using the `pairWithCode` command? This way you can pair the bot using the [linking with phone number feature](https://faq.whatsapp.com/1324084875126592).
