### ISSUE TITLE
sticker gif .webp not embedding

### ISSUE THREAD

**Issue by TukangM** [FKLC/WhatsAppToDiscord#173]
**Describe the bug**
the problem is sometime sticker (gif) from whatsapp not embedding with extension .webp

**To Reproduce**
1. send sticker gif. (whatsapp)
2. look the result on #whatsapp-bot (discord)

**Expected behavior**
sticker must embed with something tenor, discord upload file.

**Platform**
 - OS: Debian 11

**Additional Image**
![image](https://github.com/FKLC/WhatsAppToDiscord/assets/91467886/2ff0b27c-31ef-4df6-b66e-ed42b9838b9c)
![image](https://github.com/FKLC/WhatsAppToDiscord/assets/91467886/9e3080bd-88e2-4041-bffd-55cd6fe8b61f)

**Comment by Ishannaik** [comment]
**Feature Request 1: Channel Rename Command**

**Is your feature request related to a problem? Please describe.**
I often encounter a situation where random numbers appear instead of contact names for the person or for the group, making it necessary to manually readd them using start command by deleting them for identification.

**Describe the solution you'd like**
I suggest implementing an "add a rename command" feature in WA2DC's GitHub repository. This command would allow users to rename channels, addressing the issue of displaying random numbers/contact number instead of contact names. 

**Describe alternatives you've considered**
As an alternative, users could manually rename channels, but this causes the bot to disconnect from the channel.

---

**Feature Request 2: Chat History Restore Command**

**Is your feature request related to a problem? Please describe.**
Sometimes, channels get deleted during server switching/switching hosting services, creating difficulty in retrieving chat history. To address this, I propose adding a "restorechathistory [number of messages]" command to WA2DC.

**Describe the solution you'd like**
I suggest implementing a command that allows users to restore chat history in case of channel deletion and I want to recreate the dm with history. The command should be able to pull the for eg last 100 messages from DMs or save the entire chat history on DC.

---



**Feature Request 3: Updating documentation to be more detailed**

I am having trouble understand what these commands do
LastMessageStorage
publishing messages? What are they

**Comment by FKLC** [comment]
This is a Discord issue. Try uploading a animated webp, it will look like this. For example, if you try [this sample](https://www.bandisoft.com/s/webp-to-gif-converter-app/sample.webp) from [this web page](https://www.bandisoft.com/s/webp-to-gif-converter-app/), you'll see Discord wont render the image. Closing the issue for now since it isn't related to the bot.

**Comment by TukangM** [comment]
Okay... but I once sent a .webp file without bots or anything else directly from me. For some reason, sometimes it embeds itself, sometimes it doesn't embed the gif sticker

**Comment by FKLC** [comment]
I mean if you still have access to that webp file, you can probably report it to discord as a bug and wait for them to implement it properly. But since WhatsApp processes stickers in a way that Discord fails to recognize them, we can't test it with the bot because WhatsApp will process that image and make it unrecognizable for Discord again. So all we can do at the moment is, report this issue to Discord wait for them to implement a bug fix.
