### ISSUE TITLE
The bot is already on the server but it asks to be added to another one that you own

### ISSUE THREAD

**Issue by weskerty** [FKLC/WhatsAppToDiscord#189]
**Describe the bug**
The bot is already on the server but it asks to be added to another one that you own. How to make it work on an existing server?

**To Reproduce**
1 Start bot
2 add the token
3 - Request that you add it to a Server and only the servers you own appear.

**Expected behavior**

**Platform**
 - OS: W10

**Comment by FKLC** [comment]
I'm not sure if I understand the problem. Are you saying,
1) You have been using the bot, but it suddenly asked for token, and won't use the old server, or
2) You can only add the bot to the servers you own?

If it is the first option, manually fixing/repairing the settings file in the storage folder might help, but it is not very easy to do. If it is the second option, then it is because of discord's security rules. You can't add the bot to a server you don't have proper rights to. So, you would have to ask the owner to add the bot or give you the right to add the bot.

**Comment by weskerty** [comment]
Thank you. She believed she had the permits, she was wrong. I already made it work, apologies. 👉👈

**Comment by FKLC** [comment]
I see. No problem at all. Thank you!

Sent from Proton Mail Android

-------- Original Message --------
