### ISSUE TITLE
No QR Code generated once app joins discord 

### ISSUE THREAD

**Issue by nnetwalkerr** [FKLC/WhatsAppToDiscord#213]
**Describe the bug**
No QR Code generated

**Comment by nnetwalkerr** [comment]
![image](https://github.com/user-attachments/assets/07a238c8-b8ba-4e86-9b7e-6ec1f5a00c45)

**Comment by nnetwalkerr** [comment]
![image](https://github.com/user-attachments/assets/5ba80d7c-44a1-4dbd-94ec-256123dba1aa)

**Comment by EvilsSouls** [comment]
I was having the same issue, where the Discord Bot would just exit, after creating the channel. Upon inspecting the log file I saw, that the problem was misconfigured permissions. To fix this, when the bot prompts you to open the discord link to add the app to a server, you need to replace the number after "permission" to 137976212560 (I just took my best guess, on what the Bot might need, and added it as a permission). Then just add the bot to the server and it should just work.

**Comment by EvilsSouls** [comment]
(also make sure to turn on the "Message Content Intent" option in the bot settings)

**Comment by FKLC** [comment]
Please make sure you have the correct bot permissions set as described in the setup steps.
