### ISSUE TITLE
Always "online" on WA and bot starts spamming messages when it loses connection

### ISSUE THREAD

**Issue by MDproductions-dev** [FKLC/WhatsAppToDiscord#26]
1: i am hosting this on my own server and it contantly shows me as "online" in whatsapp wich is a bit wierd for others if you not respond while you are "online".

2: if i open whatsapp web on another device or the bot loses connection the bot goes haywire and spams all of my chats in discord.

**Comment by FKLC** [comment]
1. I think this issue is on your end. To show you as "Online" on WhatsApp, the bot should send presence updates, but it doesn't send anything. I tested this to confirm w/o sending presence updates, and no, just having the bot active won't show you as "Online" in WhatsApp.
2. I tried to reproduce the bug, but the bot didn't spam chats. Rather it reconnected and disconnected the other device. If you can, update the bot and reproduce the bug, and upload your `logs.txt` (log file doesn't contain any information related to you, if you still have privacy concerns you may redact that part or email to me), so that I can look into this issue. Thanks for your cooperation.

**Comment by FKLC** [comment]
1. N/A
2. With the latest release it should be fixed now please reopen the issue if it persists.
