### ISSUE TITLE
Bot starts spamming messages when it loses connection

### ISSUE THREAD

**Issue by heryoff** [FKLC/WhatsAppToDiscord#29]
Every time my phone/ server lose connection the bot start spamming all the messages again.

**Comment by FKLC** [comment]
I tried to reproduce the bug, but the bot didn't start spamming messages. If you can, please update the bot and reproduce the bug, and upload your `logs.txt` (log file doesn't contain any information related to you, if you still have privacy concerns you may redact that part or email to me), so that I can look into this issue. Thanks for your cooperation.

**Comment by FKLC** [comment]
With the latest release it should be fixed now please reopen the issue if it persists.
