### ISSUE TITLE
Virus detected? false positive?

### ISSUE THREAD

**Issue by spookycookie27** [FKLC/WhatsAppToDiscord#38]
Thanks for your hard work on this. Its really useful..

v0.3.3 triggered my antivirus... Any ideas why that would be?

**Comment by FKLC** [comment]
I don't really know. You can compile it for yourself anytime. It is most likely a false positive or some other virus may have caused it but I don't think it is likely. If you want to compile for yourself just run `go build -ldflags="-s -w" -trimpath -o WA2DC.exe WA2DC.go` with Go installed. I ran VirusTotal on both compressed and not compressed versions. Even the non compressed version gets detected as a virus by [4 out of 68](https://www.virustotal.com/gui/file/f75d73bdfc03a3563e293334626fcbd13cfe537b017ba68b455bef9776c91b1e/detection) scanners, and the compressed one gets detected as a virus by [7 out of 68](https://www.virustotal.com/gui/file/3898456095bd228b8e69da7e2e02f78f4945c8d9d797640eb07ed881106b2c97/detection) scanners. As I said, I don't really know the reason. My best guess is that it is not a widely spread binary, and programs detect it as a virus because it makes connections to various servers. I genuinely don't know why and just saying it is not a virus won't be enough, so if you want to, inspect the code, just compile for yourself, and use it at your own risk. There are some things that I don't check like the libraries I use but I count on open source contributors, but again I can't guarantee complete security. If you find this explanation satisfactory enough please close the issue. Thanks.

**Comment by spookycookie27** [comment]
Hi, thanks for responding.
I havent tried to compile it myself , I'm not up to speed with GO. I'm JS and C#.
Yeah you're probably right, it could be a vulnerability in one of the packages. Just thought it was weird that all the previous versions did not trigger the filter. I cast my beady eye over your last few commits, and all looked fine to me!  
It was Windows Defender by the way.

Anyway keep up the good work dude, it is appreciated!
