### ISSUE TITLE
Sometimes it doesn't connect to the discord's bot.

### ISSUE THREAD

**Issue by Shinobi7k** [FKLC/WhatsAppToDiscord#98]
**Describe the bug**
When I run the bridge in a lot of times it just doesn't connect to the discord's bot and doesn't show any errors in the console it just says **Running script with node. Skipping auto-update.** 
but sometimes it connects idk why.
I am using the latest version btw.

**Additional context**
I run it on [Replit](https://replit.com) and I am using [this method](https://www.youtube.com/watch?v=-ke0zEq3njU&ab_channel=M692) to run it 24/7. idk if that's related to the issue.

**Comment by FKLC** [comment]
The issue is one of the contacts you have. When you have a message from that group, the bot just fails and stops executing further. I can't copy paste it to here for some reason. VSCode can't even show it, but on notepad it is rendered as 
![image](https://user-images.githubusercontent.com/29578493/187792305-00c3ea86-dff9-4829-b0ba-533d65103169.png). This is the first time I've seen Discord not accepting a character as a text channel name. I'll look into it. Also, I deleted your logs.txt for privacy concerns.

**Comment by FKLC** [comment]
Fixed it. New release should be out in a few minutes.
